[book]
authors = ["Seb Blanchet"]
language = "en"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
site-url = "/spotify-tui/"
git-repository-url = "https://https://github.com/sebastienblanchet/spotify-tui"
